# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/mainwindow.ui'
#
# Created: Mon Aug 24 09:59:26 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(996, 715)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.data_input_group_box = QtWidgets.QGroupBox(self.centralWidget)
        self.data_input_group_box.setMaximumSize(QtCore.QSize(16777215, 281))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.data_input_group_box.setFont(font)
        self.data_input_group_box.setObjectName(_fromUtf8("data_input_group_box"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.data_input_group_box)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.offsetMarkerTableView = QtWidgets.QTableView(self.data_input_group_box)
        self.offsetMarkerTableView.setObjectName(_fromUtf8("offsetMarkerTableView"))
        self.horizontalLayout.addWidget(self.offsetMarkerTableView)
        self.off_marker_button_vlayout = QtWidgets.QVBoxLayout()
        self.off_marker_button_vlayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.off_marker_button_vlayout.setObjectName(_fromUtf8("off_marker_button_vlayout"))
        self.moveOffsetMarkerUpButton = QtWidgets.QPushButton(self.data_input_group_box)
        self.moveOffsetMarkerUpButton.setObjectName(_fromUtf8("moveOffsetMarkerUpButton"))
        self.off_marker_button_vlayout.addWidget(self.moveOffsetMarkerUpButton)
        self.moveOffsetMarkerDownButton = QtWidgets.QPushButton(self.data_input_group_box)
        self.moveOffsetMarkerDownButton.setObjectName(_fromUtf8("moveOffsetMarkerDownButton"))
        self.off_marker_button_vlayout.addWidget(self.moveOffsetMarkerDownButton)
        spacerItem = QtWidgets.QSpacerItem(28, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.off_marker_button_vlayout.addItem(spacerItem)
        self.addOffsetMarkerButton = QtWidgets.QPushButton(self.data_input_group_box)
        self.addOffsetMarkerButton.setObjectName(_fromUtf8("addOffsetMarkerButton"))
        self.off_marker_button_vlayout.addWidget(self.addOffsetMarkerButton)
        self.removeOffsetMarkerButton = QtWidgets.QPushButton(self.data_input_group_box)
        self.removeOffsetMarkerButton.setObjectName(_fromUtf8("removeOffsetMarkerButton"))
        self.off_marker_button_vlayout.addWidget(self.removeOffsetMarkerButton)
        self.horizontalLayout.addLayout(self.off_marker_button_vlayout)
        self.verticalLayout_2.addWidget(self.data_input_group_box)
        self.run_config_box = QtWidgets.QGroupBox(self.centralWidget)
        self.run_config_box.setMaximumSize(QtCore.QSize(16777215, 110))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.run_config_box.setFont(font)
        self.run_config_box.setObjectName(_fromUtf8("run_config_box"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.run_config_box)
        self.verticalLayout.setContentsMargins(2, 4, 2, 4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.importButton = QtWidgets.QPushButton(self.run_config_box)
        self.importButton.setObjectName(_fromUtf8("importButton"))
        self.horizontalLayout_2.addWidget(self.importButton)
        self.exportButton = QtWidgets.QPushButton(self.run_config_box)
        self.exportButton.setObjectName(_fromUtf8("exportButton"))
        self.horizontalLayout_2.addWidget(self.exportButton)
        spacerItem1 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.fit_type_label = QtWidgets.QLabel(self.run_config_box)
        self.fit_type_label.setObjectName(_fromUtf8("fit_type_label"))
        self.horizontalLayout_2.addWidget(self.fit_type_label)
        self.linearFitRadio = QtWidgets.QRadioButton(self.run_config_box)
        self.linearFitRadio.setChecked(True)
        self.linearFitRadio.setObjectName(_fromUtf8("linearFitRadio"))
        self.fitTypeButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.fitTypeButtonGroup.setObjectName(_fromUtf8("fitTypeButtonGroup"))
        self.fitTypeButtonGroup.addButton(self.linearFitRadio)
        self.horizontalLayout_2.addWidget(self.linearFitRadio)
        self.piecewiseFitRadio = QtWidgets.QRadioButton(self.run_config_box)
        self.piecewiseFitRadio.setObjectName(_fromUtf8("piecewiseFitRadio"))
        self.fitTypeButtonGroup.addButton(self.piecewiseFitRadio)
        self.horizontalLayout_2.addWidget(self.piecewiseFitRadio)
        self.nPiecesSpinBox = QtWidgets.QSpinBox(self.run_config_box)
        self.nPiecesSpinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.nPiecesSpinBox.setMinimum(2)
        self.nPiecesSpinBox.setMaximum(10)
        self.nPiecesSpinBox.setProperty("value", 2)
        self.nPiecesSpinBox.setObjectName(_fromUtf8("nPiecesSpinBox"))
        self.horizontalLayout_2.addWidget(self.nPiecesSpinBox)
        self.cubicFitRadio = QtWidgets.QRadioButton(self.run_config_box)
        self.cubicFitRadio.setObjectName(_fromUtf8("cubicFitRadio"))
        self.fitTypeButtonGroup.addButton(self.cubicFitRadio)
        self.horizontalLayout_2.addWidget(self.cubicFitRadio)
        spacerItem2 = QtWidgets.QSpacerItem(13, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.runButton = QtWidgets.QPushButton(self.run_config_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.runButton.setFont(font)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.horizontalLayout_2.addWidget(self.runButton)
        self.cancelButton = QtWidgets.QPushButton(self.run_config_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.plotButton = QtWidgets.QPushButton(self.run_config_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plotButton.setFont(font)
        self.plotButton.setObjectName(_fromUtf8("plotButton"))
        self.horizontalLayout_2.addWidget(self.plotButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.nItersLineEdit = QtWidgets.QLineEdit(self.run_config_box)
        self.nItersLineEdit.setObjectName(_fromUtf8("nItersLineEdit"))
        self.horizontalLayout_3.addWidget(self.nItersLineEdit)
        self.nItersLabel = QtWidgets.QLabel(self.run_config_box)
        self.nItersLabel.setObjectName(_fromUtf8("nItersLabel"))
        self.horizontalLayout_3.addWidget(self.nItersLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.zeroOffsetLineEdit = QtWidgets.QLineEdit(self.run_config_box)
        self.zeroOffsetLineEdit.setObjectName(_fromUtf8("zeroOffsetLineEdit"))
        self.horizontalLayout_3.addWidget(self.zeroOffsetLineEdit)
        self.zeroOffsetLabel = QtWidgets.QLabel(self.run_config_box)
        self.zeroOffsetLabel.setObjectName(_fromUtf8("zeroOffsetLabel"))
        self.horizontalLayout_3.addWidget(self.zeroOffsetLabel)
        spacerItem4 = QtWidgets.QSpacerItem(48, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.randSeedLineEdit = QtWidgets.QLineEdit(self.run_config_box)
        self.randSeedLineEdit.setObjectName(_fromUtf8("randSeedLineEdit"))
        self.horizontalLayout_3.addWidget(self.randSeedLineEdit)
        self.randSeedCheckBox = QtWidgets.QCheckBox(self.run_config_box)
        self.randSeedCheckBox.setChecked(True)
        self.randSeedCheckBox.setObjectName(_fromUtf8("randSeedCheckBox"))
        self.horizontalLayout_3.addWidget(self.randSeedCheckBox)
        spacerItem5 = QtWidgets.QSpacerItem(38, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.forceIncrCheckBox = QtWidgets.QCheckBox(self.run_config_box)
        self.forceIncrCheckBox.setObjectName(_fromUtf8("forceIncrCheckBox"))
        self.horizontalLayout_3.addWidget(self.forceIncrCheckBox)
        self.slipRevCheckBox = QtWidgets.QCheckBox(self.run_config_box)
        self.slipRevCheckBox.setObjectName(_fromUtf8("slipRevCheckBox"))
        self.horizontalLayout_3.addWidget(self.slipRevCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.run_config_box)
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0,0,0,0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.vlayout_for_ipython = QtWidgets.QVBoxLayout()
        self.vlayout_for_ipython.setObjectName(_fromUtf8("vlayout_for_ipython"))
        self.horizontalLayout_4.addLayout(self.vlayout_for_ipython)
        self.verticalLayout_2.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.data_input_group_box.setTitle(_translate("MainWindow", "Data Input", None))
        self.moveOffsetMarkerUpButton.setText(_translate("MainWindow", "^", None))
        self.moveOffsetMarkerDownButton.setText(_translate("MainWindow", "v", None))
        self.addOffsetMarkerButton.setText(_translate("MainWindow", "+", None))
        self.removeOffsetMarkerButton.setText(_translate("MainWindow", "-", None))
        self.run_config_box.setTitle(_translate("MainWindow", "Run Configuration", None))
        self.importButton.setText(_translate("MainWindow", "Import", None))
        self.exportButton.setText(_translate("MainWindow", "Export", None))
        self.fit_type_label.setText(_translate("MainWindow", "Fit Type", None))
        self.linearFitRadio.setText(_translate("MainWindow", "Linear", None))
        self.piecewiseFitRadio.setText(_translate("MainWindow", "Piecewise Linear", None))
        self.cubicFitRadio.setText(_translate("MainWindow", "Cubic Spline", None))
        self.runButton.setText(_translate("MainWindow", "Run", None))
        self.cancelButton.setText(_translate("MainWindow", "Cancel", None))
        self.plotButton.setText(_translate("MainWindow", "Plot", None))
        self.nItersLineEdit.setText(_translate("MainWindow", "1000", None))
        self.nItersLabel.setText(_translate("MainWindow", "Iterations", None))
        self.zeroOffsetLineEdit.setText(_translate("MainWindow", "0.", None))
        self.zeroOffsetLabel.setText(_translate("MainWindow", "Zero offset age", None))
        self.randSeedLineEdit.setText(_translate("MainWindow", "69.", None))
        self.randSeedCheckBox.setText(_translate("MainWindow", "random seed", None))
        self.forceIncrCheckBox.setText(_translate("MainWindow", "Force increasing data", None))
        self.slipRevCheckBox.setText(_translate("MainWindow", "Allow slip reversals", None))

